name: acs_upb_mobile
description: A mobile application for students at ACS UPB.

# The following defines the version and build number for the application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# ACS UPB Mobile uses semantic versioning. You can read more in the CONTRIBUTING.md file.
version: 1.2.11+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Async utility classes
  async: ^2.6.1

  # Helps with sizing text to fit container
  auto_size_text: ^3.0.0-nullsafety.0

  # Dart helper methods
  basic_utils: ^3.1.0

  # Caching utilities
  cached_network_image: ^3.0.0

  # Firebase Firestore
  cloud_firestore: ^2.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # Date & time picker widget
  datetime_picker_formfield: ^2.0.0

  # Dotted line painter
  dotted_line: ^3.0.0

  # Highlight words
#  dynamic_text_highlighting: ^2.2.0

  # Package for dynamically changing the app theme
#  dynamic_theme: ^1.0.1
  easy_dynamic_theme: ^2.2.0

  # Firebase products
  firebase_analytics: ^8.1.1
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_storage: ^8.1.1

  # Flutter SDK
  flutter:
    sdk: flutter

  # Color picker widget
  flutter_colorpicker: ^0.4.0

  # Allow using feather icons (nice outlined icons)
  flutter_feather_icons: ^2.0.0+1

  # Package that allows for supporting multiple languages
  flutter_localizations:
    sdk: flutter

  # Display markdown-formatted text
  flutter_markdown: ^0.6.2

  # Use an in-app browser to ask user for Google Calendar permission
  flutter_web_browser: ^0.14.0

  # Used for Google Calendar API
  googleapis: ^3.0.0

  # Used for getting the permission of the user to access their Google Calendar
  googleapis_auth: ^1.1.0

  # Image decoder
  image: ^3.0.2

  # Image importer
  image_picker: ^0.8.0+1

  # Web image importer
  image_picker_web: ^2.0.2

  # Interval picker widget
#  interval_time_picker: ^0.1.0

  # Displays a custom toast
  oktoast: ^3.0.0

  # App information
  package_info_plus: ^1.0.1

  # Draws pie charts
  pie_chart: ^5.0.0

  # Allows getting the position of taps
  positioned_tap_detector_2: ^1.0.0

  # Used to create preference screens
  pref: ^2.2.0

  # Dart utilities
  quiver: ^3.0.1

  # String utility methods
  recase: ^4.0.0

  # Event recurrence rule handler
  rrule: ^0.2.3

  # Async utilities
  rxdart: ^0.26.0

  # Support lock/mutex
  synchronized: ^3.0.0

  # DateTime utilities
#  time_machine: ^0.9.16

  # Time interval picker
  time_range_picker: ^2.0.1

  # Timetable widget
  timetable: ^1.0.0-alpha.0

  # URL opener
  url_launcher: ^6.0.6

  # Useful validators
  validators: ^3.0.0

  # Web scraper
  web_scraper: ^0.1.4

dev_dependencies:
  # Code analysis
  extra_pedantic: ^1.5.0

  # Simplifies updating the launcher icon
  flutter_launcher_icons: ^0.9.0

  # Simplifies updating the launcher name
#  flutter_launcher_name: ^0.0.1

  # Generates native code for adding splash screens on iOS & Android
  flutter_native_splash: ^1.1.8+4

  # Testing framework
  flutter_test:
    sdk: flutter

  # Helps with generating Dart code with the messages from `.arb` files
#  intl_translation: ^0.17.1

  # Mocking utility used for testing
  mockito: ^5.0.9

  # Testing utils
  network_image_mock: ^2.0.1

  # Provider platform interfaces of federated flutter plugins, for testing (like url_launcher)
  plugin_platform_interface: ^2.0.0

  # Using Provider for state management
  provider: ^5.0.0

dependency_overrides:
  # Temporary workaround to bypass intl_translation incompatibility
#  intl: ^0.17.0-nullsafety.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/illustrations/
  - assets/images/
#  - packages/time_machine/data/cultures/cultures.bin
#  - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
  - family: CustomIcons
    fonts:
    - asset: assets/fonts/CustomIcons/CustomIcons.ttf
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat/Montserrat-Thin.otf
      weight: 100
    - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.otf
      weight: 100
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.otf
      weight: 200
    - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.otf
      weight: 200
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-Light.otf
      weight: 300
    - asset: assets/fonts/Montserrat/Montserrat-LightItalic.otf
      weight: 300
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-Regular.otf
      weight: 400
    - asset: assets/fonts/Montserrat/Montserrat-Italic.otf
      weight: 400
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-Medium.otf
      weight: 500
    - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.otf
      weight: 500
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-SemiBold.otf
      weight: 600
    - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.otf
      weight: 600
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
      weight: 700
    - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.otf
      weight: 700
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.otf
      weight: 800
    - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.otf
      weight: 800
      style: italic
    - asset: assets/fonts/Montserrat/Montserrat-Black.otf
      weight: 900
    - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.otf
      weight: 900
      style: italic

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/acs_logo.png"

flutter_launcher_name:
  name: "ACS UPB"

flutter_native_splash:
  image: assets/icons/acs_logo.png
  color: "#ffffff"
