name: acs_upb_mobile
description: A mobile application for students at ACS UPB.

# The following defines the version and build number for the application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Package for dynamically changing the app theme
  dynamic_theme: ^1.0.1

  # Package that allows for supporting multiple languages
  flutter_localizations:
    sdk: flutter

  # Used to create preference screens
  preferences: ^5.1.0

  # Allows querying the app version number
  package_info: ^0.4.0+13

  # Firebase products
  firebase:
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.5+2
  firebase_auth_web: ^0.1.2
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.3

  # Dart helper methods
  basic_utils: ^1.2.0
  recase: ^3.0.0
  validators: ^2.0.0

  # Helps with sizing text to fit container
  auto_size_text: ^2.1.0

  # Displays a custom toast
  oktoast: ^2.3.1+1

  # Caching utilities
  cached_network_image: ^2.0.0

  # URL opener
  url_launcher: ^5.4.2

  # Expandable widget
  expandable: ^4.1.2

  # Async utility classes
  async: ^2.4.0

  # Timetable widget
  timetable: ^0.2.0

  # Color picker widget
  flutter_colorpicker: ^0.3.4

  # Date & time picker widget
  datetime_picker_formfield: ^1.0.0

  # Allows getting the position of taps
  positioned_tap_detector: ^1.0.3

  # Draws pie charts
  pie_chart: ^3.1.1

  # Adds Dart utilities
  quiver: ^2.1.3

  # Image importer
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: 1.8.0+1

  # Helps with generating Dart code with the messages from `.arb` files
  intl_translation: ^0.17.1

  # Simplifies updating the launcher icon
  flutter_launcher_icons: ^0.7.4

  # Simplifies updating the launcher name
  flutter_launcher_name: ^0.0.1

  # Generates native code for adding splash screens on iOS & Android
  flutter_native_splash: ^0.1.9

  # Using Provider for state management
  provider: ^4.0.4

  # Mocking utility used for testing
  mockito: ^4.1.1

  # Provider platform interfaces of federated flutter plugins, for testing (like url_launcher)
  plugin_platform_interface: ^1.0.0

  # Testing utils
  network_image_mock: ^1.0.1

dependency_overrides:
  # Workaround because timetable depends on pedantic 1.9.0 while flutter_test depends on pedantic 1.8.0
  pedantic: 1.9.0

  # Workaround because timetable depends on dartx 0.3.0 which is incompatible with flutter_test
  dartx: ^0.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/websites/
    - assets/illustrations/
    - assets/images/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.otf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.otf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.otf
          weight: 900
          style: italic

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/acs_logo.png"

flutter_launcher_name:
  name: "ACS UPB"

flutter_native_splash:
  image: assets/icons/acs_logo.png
  color: "#ffffff"
